// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace SharpEmu.Libs.SaveData
{
    internal sealed partial class SaveDataMetadataContext
    {
        private static readonly global::System.Text.Json.JsonEncodedText PropName_title = global::System.Text.Json.JsonEncodedText.Encode("title");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_subTitle = global::System.Text.Json.JsonEncodedText.Encode("subTitle");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_detail = global::System.Text.Json.JsonEncodedText.Encode("detail");
        private static readonly global::System.Text.Json.JsonEncodedText PropName_userParam = global::System.Text.Json.JsonEncodedText.Encode("userParam");
    }
}
