// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace SharpEmu.Libs.SaveData
{
    internal sealed partial class SaveDataMetadataContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<uint>? _UInt32;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<uint> UInt32
        #nullable enable annotations
        {
            get => _UInt32 ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<uint>)Options.GetTypeInfo(typeof(uint));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<uint> Create_UInt32(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<uint>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<uint> jsonTypeInfo))
            {
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateValueInfo<uint>(options, global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.UInt32Converter);
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }
    }
}
