// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace SharpEmu.Libs.SaveData
{
    internal sealed partial class SaveDataMetadataContext : global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver
    {
        /// <inheritdoc/>
        public override global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? GetTypeInfo(global::System.Type type)
        {
            Options.TryGetTypeInfo(type, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? typeInfo);
            return typeInfo;
        }

        global::System.Text.Json.Serialization.Metadata.JsonTypeInfo? global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(global::System.Type type, global::System.Text.Json.JsonSerializerOptions options)
        {
            if (type == typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata))
            {
                return Create_SaveDataMetadata(options);
            }
            if (type == typeof(string))
            {
                return Create_String(options);
            }
            if (type == typeof(uint))
            {
                return Create_UInt32(options);
            }
            return null;
        }
    }
}
