// <auto-generated/>

#nullable enable annotations
#nullable disable warnings

// Suppress warnings about [Obsolete] member usage in generated code.
#pragma warning disable CS0612, CS0618

namespace SharpEmu.Libs.SaveData
{
    internal sealed partial class SaveDataMetadataContext
    {
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::SharpEmu.Libs.SaveData.SaveDataMetadata>? _SaveDataMetadata;
        
        /// <summary>
        /// Defines the source generated JSON serialization contract metadata for a given type.
        /// </summary>
        #nullable disable annotations // Marking the property type as nullable-oblivious.
        public global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::SharpEmu.Libs.SaveData.SaveDataMetadata> SaveDataMetadata
        #nullable enable annotations
        {
            get => _SaveDataMetadata ??= (global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::SharpEmu.Libs.SaveData.SaveDataMetadata>)Options.GetTypeInfo(typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata));
        }
        
        private global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::SharpEmu.Libs.SaveData.SaveDataMetadata> Create_SaveDataMetadata(global::System.Text.Json.JsonSerializerOptions options)
        {
            if (!TryGetTypeInfoForRuntimeCustomConverter<global::SharpEmu.Libs.SaveData.SaveDataMetadata>(options, out global::System.Text.Json.Serialization.Metadata.JsonTypeInfo<global::SharpEmu.Libs.SaveData.SaveDataMetadata> jsonTypeInfo))
            {
                var objectInfo = new global::System.Text.Json.Serialization.Metadata.JsonObjectInfoValues<global::SharpEmu.Libs.SaveData.SaveDataMetadata>
                {
                    ObjectCreator = null,
                    ObjectWithParameterizedConstructorCreator = static args => new global::SharpEmu.Libs.SaveData.SaveDataMetadata(){ Title = (string)args[0], SubTitle = (string)args[1], Detail = (string)args[2], UserParam = (uint)args[3] },
                    PropertyMetadataInitializer = _ => SaveDataMetadataPropInit(options),
                    ConstructorParameterMetadataInitializer = SaveDataMetadataCtorParamInit,
                    ConstructorAttributeProviderFactory = static () => typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata).GetConstructor(InstanceMemberBindingFlags, binder: null, global::System.Array.Empty<global::System.Type>(), modifiers: null),
                    SerializeHandler = SaveDataMetadataSerializeHandler,
                };
                
                jsonTypeInfo = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreateObjectInfo<global::SharpEmu.Libs.SaveData.SaveDataMetadata>(options, objectInfo);
                jsonTypeInfo.NumberHandling = null;
            }
        
            jsonTypeInfo.OriginatingResolver = this;
            return jsonTypeInfo;
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[] SaveDataMetadataPropInit(global::System.Text.Json.JsonSerializerOptions options)
        {
            var properties = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfo[4];

            var info0 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata),
                Converter = null,
                Getter = static obj => ((global::SharpEmu.Libs.SaveData.SaveDataMetadata)obj).Title,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Title",
                JsonPropertyName = "title",
                AttributeProviderFactory = static () => typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata).GetProperty("Title", InstanceMemberBindingFlags, null, typeof(string), global::System.Array.Empty<global::System.Type>(), null),
            };
            
            properties[0] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info0);
            properties[0].IsGetNullable = false;
            properties[0].IsSetNullable = false;

            var info1 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata),
                Converter = null,
                Getter = static obj => ((global::SharpEmu.Libs.SaveData.SaveDataMetadata)obj).SubTitle,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "SubTitle",
                JsonPropertyName = "subTitle",
                AttributeProviderFactory = static () => typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata).GetProperty("SubTitle", InstanceMemberBindingFlags, null, typeof(string), global::System.Array.Empty<global::System.Type>(), null),
            };
            
            properties[1] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info1);
            properties[1].IsGetNullable = false;
            properties[1].IsSetNullable = false;

            var info2 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<string>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata),
                Converter = null,
                Getter = static obj => ((global::SharpEmu.Libs.SaveData.SaveDataMetadata)obj).Detail,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "Detail",
                JsonPropertyName = "detail",
                AttributeProviderFactory = static () => typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata).GetProperty("Detail", InstanceMemberBindingFlags, null, typeof(string), global::System.Array.Empty<global::System.Type>(), null),
            };
            
            properties[2] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<string>(options, info2);
            properties[2].IsGetNullable = false;
            properties[2].IsSetNullable = false;

            var info3 = new global::System.Text.Json.Serialization.Metadata.JsonPropertyInfoValues<uint>
            {
                IsProperty = true,
                IsPublic = true,
                IsVirtual = false,
                DeclaringType = typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata),
                Converter = null,
                Getter = static obj => ((global::SharpEmu.Libs.SaveData.SaveDataMetadata)obj).UserParam,
                Setter = static (obj, value) => throw new global::System.InvalidOperationException("Setting init-only properties is not supported in source generation mode."),
                IgnoreCondition = null,
                HasJsonInclude = false,
                IsExtensionData = false,
                NumberHandling = null,
                PropertyName = "UserParam",
                JsonPropertyName = "userParam",
                AttributeProviderFactory = static () => typeof(global::SharpEmu.Libs.SaveData.SaveDataMetadata).GetProperty("UserParam", InstanceMemberBindingFlags, null, typeof(uint), global::System.Array.Empty<global::System.Type>(), null),
            };
            
            properties[3] = global::System.Text.Json.Serialization.Metadata.JsonMetadataServices.CreatePropertyInfo<uint>(options, info3);

            return properties;
        }

        // Intentionally not a static method because we create a delegate to it. Invoking delegates to instance
        // methods is almost as fast as virtual calls. Static methods need to go through a shuffle thunk.
        private void SaveDataMetadataSerializeHandler(global::System.Text.Json.Utf8JsonWriter writer, global::SharpEmu.Libs.SaveData.SaveDataMetadata? value)
        {
            if (value is null)
            {
                writer.WriteNullValue();
                return;
            }
            
            writer.WriteStartObject();

            writer.WriteString(PropName_title, ((global::SharpEmu.Libs.SaveData.SaveDataMetadata)value).Title);
            writer.WriteString(PropName_subTitle, ((global::SharpEmu.Libs.SaveData.SaveDataMetadata)value).SubTitle);
            writer.WriteString(PropName_detail, ((global::SharpEmu.Libs.SaveData.SaveDataMetadata)value).Detail);
            writer.WriteNumber(PropName_userParam, ((global::SharpEmu.Libs.SaveData.SaveDataMetadata)value).UserParam);

            writer.WriteEndObject();
        }

        private static global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[] SaveDataMetadataCtorParamInit() => new global::System.Text.Json.Serialization.Metadata.JsonParameterInfoValues[]
        {
            new()
            {
                Name = "Title",
                ParameterType = typeof(string),
                Position = 0,
                IsNullable = false,
                IsMemberInitializer = true,
            },

            new()
            {
                Name = "SubTitle",
                ParameterType = typeof(string),
                Position = 1,
                IsNullable = false,
                IsMemberInitializer = true,
            },

            new()
            {
                Name = "Detail",
                ParameterType = typeof(string),
                Position = 2,
                IsNullable = false,
                IsMemberInitializer = true,
            },

            new()
            {
                Name = "UserParam",
                ParameterType = typeof(uint),
                Position = 3,
                IsNullable = false,
                IsMemberInitializer = true,
            },
        };
    }
}
