param([Parameter(Mandatory=$true)][string]$PackageRoot)
. (Join-Path $PSScriptRoot 'common.ps1') -PackageRoot $PackageRoot
& (Join-Path $PSScriptRoot 'validate_package.ps1') -PackageRoot $PackageRoot
$s=Assert-StructuralContracts
if(-not $s.Presenter.Contains('SHARPEMU_V74_0_84_SUBMISSION_HEADROOM_ADAPTIVE')){throw "$script:Tag V84 marker missing. Run RUN_3 first."}
$exe=Find-SharpEmuExe;if($null -eq $exe){throw "$script:Tag SharpEmu executable not found. Run RUN_3 first."}
$eboot='F:\JOGOSPS5\PPSA01341\eboot.bin';if(-not(Test-Path -LiteralPath $eboot -PathType Leaf)){throw "$script:Tag Demon''s Souls eboot not found: $eboot"}
$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$log=Join-Path $script:PatchesRoot "SharpEmu_V74_0_84_SUBMISSION_THROUGHPUT_$stamp.log";$summary=Join-Path $script:PatchesRoot "SharpEmu_V74_0_84_SUBMISSION_THROUGHPUT_SUMMARY_$stamp.txt";$zip=Join-Path $script:PatchesRoot "SharpEmu_V74_0_84_SUBMISSION_THROUGHPUT_RESULT_$stamp.zip"
Write-Host '';Write-Host "$script:Tag TESTE DE THROUGHPUT V84:" -ForegroundColor Cyan;Write-Host '1. Deixe passar pelos videos e chegar ao mesmo trecho de ~2.2 FPS.';Write-Host '2. Mantenha 2-3 minutos no trecho de UI/guest render para steady-state.';Write-Host '3. Feche normalmente.';Write-Host "$script:Tag RuntimeLog=$log" -ForegroundColor Cyan;Write-Host "$script:Tag Summary=$summary" -ForegroundColor Cyan;Write-Host "$script:Tag ResultZip=$zip" -ForegroundColor Cyan
$oldFair=$env:SHARPEMU_KYTY_COMPUTE_SUBMISSION_FAIRNESS;$oldAdapt=$env:SHARPEMU_ADAPTIVE_UNIFIED_COMPUTE;$oldNB=$env:SHARPEMU_NONBLOCKING_ORDERED_VISIBILITY;$oldBurst=$env:SHARPEMU_KYTY_QUEUE_SUBMISSION_BURST;$exitCode=-1
try{$env:SHARPEMU_KYTY_COMPUTE_SUBMISSION_FAIRNESS='1';$env:SHARPEMU_ADAPTIVE_UNIFIED_COMPUTE='1';$env:SHARPEMU_NONBLOCKING_ORDERED_VISIBILITY='1';$env:SHARPEMU_KYTY_QUEUE_SUBMISSION_BURST='2';$psi=New-Object System.Diagnostics.ProcessStartInfo;$psi.FileName=$exe;$psi.WorkingDirectory=Split-Path -Parent $exe;$psi.UseShellExecute=$false;$psi.Arguments=(Quote-ProcessArgument $eboot)+' --log-file '+(Quote-ProcessArgument $log);$proc=New-Object System.Diagnostics.Process;$proc.StartInfo=$psi;[void]$proc.Start();$proc.WaitForExit();$exitCode=$proc.ExitCode}finally{if($null -eq $oldFair){Remove-Item Env:SHARPEMU_KYTY_COMPUTE_SUBMISSION_FAIRNESS -ErrorAction SilentlyContinue}else{$env:SHARPEMU_KYTY_COMPUTE_SUBMISSION_FAIRNESS=$oldFair};if($null -eq $oldAdapt){Remove-Item Env:SHARPEMU_ADAPTIVE_UNIFIED_COMPUTE -ErrorAction SilentlyContinue}else{$env:SHARPEMU_ADAPTIVE_UNIFIED_COMPUTE=$oldAdapt};if($null -eq $oldNB){Remove-Item Env:SHARPEMU_NONBLOCKING_ORDERED_VISIBILITY -ErrorAction SilentlyContinue}else{$env:SHARPEMU_NONBLOCKING_ORDERED_VISIBILITY=$oldNB};if($null -eq $oldBurst){Remove-Item Env:SHARPEMU_KYTY_QUEUE_SUBMISSION_BURST -ErrorAction SilentlyContinue}else{$env:SHARPEMU_KYTY_QUEUE_SUBMISSION_BURST=$oldBurst}}
$out=New-Object System.Collections.Generic.List[string];$out.Add('[V74.0.84] Submission Headroom + Adaptive Unified Compute diagnostic');$out.Add("ExitCode=$exitCode");$out.Add('fairness_test=1 adaptive_unified_test=1 nonblocking_visibility_test=1 queue_burst_test=2')
if(-not(Test-Path -LiteralPath $log)){$out.Add('runtime_log_present=False')}else{$out.Add('runtime_log_present=True');$lines=[System.IO.File]::ReadAllLines($log)
function CountMarker([string]$marker){$n=0;foreach($line in $lines){if($line.Contains($marker)){$n++}};return $n}
function MaxCounter([string]$marker){$mx=[int64]0;foreach($line in $lines){if(-not $line.Contains($marker)){continue};$m=[regex]::Match($line,'count=(\d+)');if($m.Success){$v=[int64]$m.Groups[1].Value;if($v -gt $mx){$mx=$v}}};return $mx}
function MetricFiltered([string]$marker,[string]$token,[double]$min,[double]$max){$vals=New-Object System.Collections.Generic.List[double];foreach($line in $lines){if(-not $line.Contains($marker)){continue};$m=[regex]::Match($line,[regex]::Escape($token)+'=([0-9]+(?:[.,][0-9]+)?)');if($m.Success){$v=0.0;if([double]::TryParse($m.Groups[1].Value.Replace(',','.'),[System.Globalization.NumberStyles]::Float,[System.Globalization.CultureInfo]::InvariantCulture,[ref]$v)){if($v -ge $min -and $v -le $max){$vals.Add($v)}}}};if($vals.Count -eq 0){return 'count=0'};$sum=0.0;$mx=0.0;foreach($v in $vals){$sum+=$v;if($v -gt $mx){$mx=$v}};return ('count={0} avg_ms={1:F3} max_ms={2:F3}' -f $vals.Count,($sum/$vals.Count),$mx)}
function MaxMem([string]$token){$mx=[int64]0;foreach($line in $lines){if(-not $line.Contains('[MEM]')){continue};$m=[regex]::Match($line,[regex]::Escape($token)+'=(\d+)');if($m.Success){$v=[int64]$m.Groups[1].Value;if($v -gt $mx){$mx=$v}}};return $mx}
function LastPayloadBatchAvg{$last='';foreach($line in $lines){if($line.Contains('[V74.0.56.20][PAYLOAD_BATCH_SUBMIT]')){$last=$line}};if([string]::IsNullOrWhiteSpace($last)){return 'none'};$m=[regex]::Match($last,'count=(\d+).*?work=(\d+).*?total_work=(\d+).*?avg=([0-9]+(?:[.,][0-9]+)?)');if(-not $m.Success){return 'unparsed'};return ('count={0} last_work={1} total_work={2} avg={3}' -f $m.Groups[1].Value,$m.Groups[2].Value,$m.Groups[3].Value,$m.Groups[4].Value.Replace(',','.'))}
$out.Add("first_frame=$(CountMarker 'Vulkan VideoOut presented first frame')");$out.Add("device_lost=$(CountMarker 'Vulkan device lost')");$out.Add("adaptive_unified_max_counter=$(MaxCounter '[V74.0.56.16][ADAPTIVE_UNIFIED_COMPUTE]')");$out.Add("cross_work_overcommit_max_counter=$(MaxCounter '[V74.0.43][CROSS_WORK_OVERCOMMIT]')");$out.Add("submission_overcommit_max_counter=$(MaxCounter '[V74.0.33][SUBMISSION_OVERCOMMIT]')");$out.Add("legacy_capacity_yield_max_counter=$(MaxCounter '[V74.0.56.16][CAPACITY_YIELD]')");$out.Add("hard_capacity_yield_max_counter=$(MaxCounter '[V74.0.33][SUBMISSION_CAPACITY_YIELD]')");$out.Add("ordered_visibility_defer_max_counter=$(MaxCounter '[V74.0.29.3][ORDERED_VISIBILITY_DEFER]')");$out.Add("queue_timeline_block_max_counter=$(MaxCounter '[V74.0.42][QUEUE_TIMELINE_BLOCK]')");$out.Add("payload_batch=$(LastPayloadBatchAvg)");$out.Add("parser_escape_logged=$(CountMarker '[PARSER_ESCAPE]')");$out.Add("large_snapshot_logged=$(CountMarker 'large_texture_cpu_snapshot')");$out.Add("slow_wait_steady_le4s: $(MetricFiltered '[SLOW_WAIT_PRODUCER]' 'waited_ms' 0 4000)");$out.Add("slow_wait_video_gt4s: $(MetricFiltered '[SLOW_WAIT_PRODUCER]' 'waited_ms' 4000.0001 60000)");$out.Add("gate_wait_le4s: $(MetricFiltered '[DEDICATED_WAIT_DRAIN]' 'gate_wait_ms' 0 4000)");$out.Add("mem_max_alloc2s_mb=$(MaxMem 'alloc2s_mb')");$out.Add("mem_max_working_mb=$(MaxMem 'working_mb')");$out.Add("mem_max_private_mb=$(MaxMem 'private_mb')");$out.Add('target_frame_budget_60fps_ms=16.667')}
$out|Set-Content -LiteralPath $summary -Encoding UTF8;Write-Host '';Get-Content -LiteralPath $summary|ForEach-Object{Write-Host $_};$items=New-Object System.Collections.Generic.List[string];if(Test-Path -LiteralPath $log){$items.Add($log)};if(Test-Path -LiteralPath $summary){$items.Add($summary)};$recent=Get-ChildItem -LiteralPath $script:PatchesRoot -Filter 'SharpEmu_V74_0_84_APPLY_BUILD_*.log' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTime -Descending|Select-Object -First 1;if($null -ne $recent){$items.Add($recent.FullName)};if($items.Count -gt 0){if(Test-Path -LiteralPath $zip){Remove-Item $zip -Force};Compress-Archive -LiteralPath $items.ToArray() -DestinationPath $zip -CompressionLevel Optimal;Write-Host "$script:Tag RESULT ZIP: $zip" -ForegroundColor Green}
