// <auto-generated/>
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/System/Library/Frameworks/Metal.framework/Metal", EntryPoint = "MTLCreateSystemDefaultDevice", ExactSpelling = true)]
        public static extern partial nint MTLCreateSystemDefaultDevice();
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "10.0.14.32716")]
        [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        private static partial nint objc_getClass(string name)
        {
            byte* __name_native = default;
            nint __retVal = default;
            // Setup - Perform required setup.
            scoped global::System.Runtime.InteropServices.Marshalling.Utf8StringMarshaller.ManagedToUnmanagedIn __name_native__marshaller = new();
            try
            {
                // Marshal - Convert managed data to native data.
                __name_native__marshaller.FromManaged(name, stackalloc byte[global::System.Runtime.InteropServices.Marshalling.Utf8StringMarshaller.ManagedToUnmanagedIn.BufferSize]);
                {
                    // PinnedMarshal - Convert managed data to native data that requires the managed data to be pinned.
                    __name_native = __name_native__marshaller.ToUnmanaged();
                    __retVal = __PInvoke(__name_native);
                }
            }
            finally
            {
                // CleanupCallerAllocated - Perform cleanup of caller allocated resources.
                __name_native__marshaller.Free();
            }

            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_getClass", ExactSpelling = true)]
            static extern unsafe nint __PInvoke(byte* __name_native);
        }
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "10.0.14.32716")]
        [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        private static partial nint sel_registerName(string name)
        {
            byte* __name_native = default;
            nint __retVal = default;
            // Setup - Perform required setup.
            scoped global::System.Runtime.InteropServices.Marshalling.Utf8StringMarshaller.ManagedToUnmanagedIn __name_native__marshaller = new();
            try
            {
                // Marshal - Convert managed data to native data.
                __name_native__marshaller.FromManaged(name, stackalloc byte[global::System.Runtime.InteropServices.Marshalling.Utf8StringMarshaller.ManagedToUnmanagedIn.BufferSize]);
                {
                    // PinnedMarshal - Convert managed data to native data that requires the managed data to be pinned.
                    __name_native = __name_native__marshaller.ToUnmanaged();
                    __retVal = __PInvoke(__name_native);
                }
            }
            finally
            {
                // CleanupCallerAllocated - Perform cleanup of caller allocated resources.
                __name_native__marshaller.Free();
            }

            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "sel_registerName", ExactSpelling = true)]
            static extern unsafe nint __PInvoke(byte* __name_native);
        }
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_autoreleasePoolPush", ExactSpelling = true)]
        public static extern partial nint objc_autoreleasePoolPush();
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_autoreleasePoolPop", ExactSpelling = true)]
        public static extern partial void objc_autoreleasePoolPop(nint pool);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial nint Send(nint receiver, nint selector);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial ulong SendGpuResourceId(nint receiver, nint selector);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial nint Send(nint receiver, nint selector, nint argument);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "10.0.14.32716")]
        [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        public static partial nint Send(nint receiver, nint selector, nint argument, ref nint error)
        {
            nint __retVal;
            // Pin - Pin data in preparation for calling the P/Invoke.
            fixed (nint* __error_native = &error)
            {
                __retVal = __PInvoke(receiver, selector, argument, __error_native);
            }

            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
            static extern unsafe nint __PInvoke(nint __receiver_native, nint __selector_native, nint __argument_native, nint* __error_native);
        }
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "10.0.14.32716")]
        [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        public static partial nint Send(nint receiver, nint selector, nint argument0, nint argument1, ref nint error)
        {
            nint __retVal;
            // Pin - Pin data in preparation for calling the P/Invoke.
            fixed (nint* __error_native = &error)
            {
                __retVal = __PInvoke(receiver, selector, argument0, argument1, __error_native);
            }

            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
            static extern unsafe nint __PInvoke(nint __receiver_native, nint __selector_native, nint __argument0_native, nint __argument1_native, nint* __error_native);
        }
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial nint SendAtIndex(nint receiver, nint selector, nuint index);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "10.0.14.32716")]
        [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        public static partial bool SendBool(nint receiver, nint selector)
        {
            bool __retVal;
            sbyte __retVal_native;
            {
                __retVal_native = __PInvoke(receiver, selector);
            }

            // Unmarshal - Convert native data to managed data.
            __retVal = __retVal_native != 0;
            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
            static extern unsafe sbyte __PInvoke(nint __receiver_native, nint __selector_native);
        }
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "10.0.14.32716")]
        [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        public static partial bool SendBool(nint receiver, nint selector, nint argument)
        {
            bool __retVal;
            sbyte __retVal_native;
            {
                __retVal_native = __PInvoke(receiver, selector, argument);
            }

            // Unmarshal - Convert native data to managed data.
            __retVal = __retVal_native != 0;
            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
            static extern unsafe sbyte __PInvoke(nint __receiver_native, nint __selector_native, nint __argument_native);
        }
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial double SendDouble(nint receiver, nint selector);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoid(nint receiver, nint selector);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoid(nint receiver, nint selector, nint argument);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoid(nint receiver, nint selector, nint argument0, nint argument1);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoidSwizzle(nint receiver, nint selector, global::SharpEmu.Libs.Gpu.Metal.MtlTextureSwizzleChannels channels);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "10.0.14.32716")]
        [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        public static partial void SendVoidBool(nint receiver, nint selector, bool argument)
        {
            sbyte __argument_native;
            // Marshal - Convert managed data to native data.
            __argument_native = (sbyte)(argument ? 1 : 0);
            {
                __PInvoke(receiver, selector, __argument_native);
            }

            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
            static extern unsafe void __PInvoke(nint __receiver_native, nint __selector_native, sbyte __argument_native);
        }
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoidDouble(nint receiver, nint selector, double argument);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoidSize(nint receiver, nint selector, global::SharpEmu.Libs.Gpu.Metal.CGSize size);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoidClearColor(nint receiver, nint selector, global::SharpEmu.Libs.Gpu.Metal.MtlClearColor color);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoidBlendColor(nint receiver, nint selector, float red, float green, float blue, float alpha);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoidViewport(nint receiver, nint selector, global::SharpEmu.Libs.Gpu.Metal.MtlViewport viewport);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendSetAtIndex(nint receiver, nint selector, nint value, nuint index);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoidCopyTexture(nint receiver, nint selector, nint source, nint destination);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial nint SendBuffer(nint receiver, nint selector, nint bytes, nuint length, nuint options);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial nint SendNewBuffer(nint receiver, nint selector, nuint length, nuint options);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendCopyTextureToBuffer(nint receiver, nint selector, nint sourceTexture, nuint sourceSlice, nuint sourceLevel, global::SharpEmu.Libs.Gpu.Metal.MtlOrigin sourceOrigin, global::SharpEmu.Libs.Gpu.Metal.MtlSize sourceSize, nint destinationBuffer, nuint destinationOffset, nuint destinationBytesPerRow, nuint destinationBytesPerImage);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendCopyBufferToTexture(nint receiver, nint selector, nint sourceBuffer, nuint sourceOffset, nuint sourceBytesPerRow, nuint sourceBytesPerImage, global::SharpEmu.Libs.Gpu.Metal.MtlSize sourceSize, nint destinationTexture, nuint destinationSlice, nuint destinationLevel, global::SharpEmu.Libs.Gpu.Metal.MtlOrigin destinationOrigin);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendDispatch(nint receiver, nint selector, global::SharpEmu.Libs.Gpu.Metal.MtlSize threadgroups, global::SharpEmu.Libs.Gpu.Metal.MtlSize threadsPerThreadgroup);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendSetBuffer(nint receiver, nint selector, nint buffer, nuint offset, nuint index);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendVoidScissor(nint receiver, nint selector, global::SharpEmu.Libs.Gpu.Metal.MtlScissorRect rect);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendDrawPrimitivesInstanced(nint receiver, nint selector, nuint primitiveType, nuint vertexStart, nuint vertexCount, nuint instanceCount);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendDrawIndexedPrimitives(nint receiver, nint selector, nuint primitiveType, nuint indexCount, nuint indexType, nint indexBuffer, nuint indexBufferOffset, nuint instanceCount);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Interop.LibraryImportGenerator", "10.0.14.32716")]
        [global::System.Runtime.CompilerServices.SkipLocalsInitAttribute]
        public static partial nint SendTextureDescriptor(nint receiver, nint selector, nuint pixelFormat, nuint width, nuint height, bool mipmapped)
        {
            sbyte __mipmapped_native;
            nint __retVal;
            // Marshal - Convert managed data to native data.
            __mipmapped_native = (sbyte)(mipmapped ? 1 : 0);
            {
                __retVal = __PInvoke(receiver, selector, pixelFormat, width, height, __mipmapped_native);
            }

            return __retVal;
            // Local P/Invoke
            [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
            static extern unsafe nint __PInvoke(nint __receiver_native, nint __selector_native, nuint __pixelFormat_native, nuint __width_native, nuint __height_native, sbyte __mipmapped_native);
        }
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendReplaceRegion(nint receiver, nint selector, global::SharpEmu.Libs.Gpu.Metal.MtlRegion region, nuint mipmapLevel, nint bytes, nuint bytesPerRow);
    }
}
namespace SharpEmu.Libs.Gpu.Metal
{
    internal static unsafe partial class MetalNative
    {
        [global::System.Runtime.InteropServices.DllImportAttribute("/usr/lib/libobjc.A.dylib", EntryPoint = "objc_msgSend", ExactSpelling = true)]
        public static extern partial void SendDrawPrimitives(nint receiver, nint selector, nuint primitiveType, nuint vertexStart, nuint vertexCount);
    }
}
