// Copyright (C) 2026 SharpEmu Emulator Project
// SPDX-License-Identifier: GPL-2.0-or-later

namespace SharpEmu.Libs.Media;

// Generated by V31.7.16 from the user's audited Demon's Souls EBOOT and BK2 headers.
internal static class DemonSoulsOpeningTimelineProfileV31716
{
    internal const string EbootSha256 = "22DD832BAE21ABEB57FC66074D2BFA5F4C53F6EFED4544A9BE6B9E0D0316130E";
    internal const long StartIntroFileOffset = 38857078;
    internal const long MusicSkipIntroFileOffset = 38389813;
    internal const long MusicManagerFileOffset = 38197956;
    internal const long BinkDataSourceFileOffset = 38856941;

    internal const uint LogoIntroFrames = 360u;
    internal const uint LogoIntroFpsNumerator = 30u;
    internal const uint LogoIntroFpsDenominator = 1u;

    internal const uint AttractFrames = 3521u;
    internal const uint AttractFpsNumerator = 30u;
    internal const uint AttractFpsDenominator = 1u;

    internal const double LogoIntroDurationSeconds = 12.000000000;
    internal const double AttractDurationSeconds = 117.366666667;
}